# 🔒 Safety Policy for Vanta Ledger
# Version: Safety CLI 3.0
# Purpose: Security scanning configuration

# Ignore low severity vulnerabilities
ignore-cvss-severity-below: 4.0

# Continue scanning even if vulnerabilities are found
continue-on-vulnerability-error: true

# Ignore unpinned requirements warnings
ignore-unpinned-requirements: true
