version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: vanta_ledger_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: vanta_ledger
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - vanta_network
    command: mongod --auth --bind_ip_all

  mongo-express:
    image: mongo-express:latest
    container_name: vanta_ledger_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - vanta_network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  vanta_network:
    driver: bridge 