name: vanta_ledger_flutter
version: 1.0.0+1
description: A modern, cross-platform personal finance app with a beautiful dark purple theme.

publish_to: 'none'

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  intl: ^0.19.0
  flutter_local_notifications: ^17.0.0
  biometric_storage: ^5.0.0
  file_picker: ^10.2.0
  share_plus: ^7.2.1
  pdf: ^3.10.4
  printing: ^5.12.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.2.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  animated_bottom_navigation_bar: ^1.2.0
  flutter_staggered_animations: ^1.1.1
  fluttertoast: ^8.2.4
  onboarding: ^3.1.0
  fl_chart: ^0.66.0
  csv: ^5.0.2
  local_auth: ^2.1.8
  timezone: ^0.9.4
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/ 