name: Security Audit

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: '0 6 * * 1'

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pip-audit
        run: pip install pip-audit
      - name: Audit backend requirements
        run: pip-audit -r backend/requirements.txt --strict || true
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install bandit
        run: pip install bandit
      - name: Run bandit
        run: bandit -r src -lll -q || true